SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR TAMANHO = '470ml';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' AND TAMANHO = '470ml';

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' AND TAMANHO = '470ml');

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' OR TAMANHO = '470ml');

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' AND NOT (TAMANHO = '470ml'));

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('Laranja', 'Manga');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja' OR SABOR = 'Manga';

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro', 'São Paulo') AND IDADE >= 20;

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro', 'São Paulo') AND (IDADE >= 19
    AND IDADE <= 21);