ABS(); /* Valor absoluto de um número */

/* Funções agregadoras */
SUM();
MAX();
MIN();
COUNT();
AVG();

/* Funções de arredondamento */
CEILING();
FLOOR();
ROUND();

SELECT (23+((25-2)/2)*45) AS RESULTADO;

SELECT CEILING(12.3333333) AS RESULTADO;

SELECT ROUND(12.333333) AS RESULTADO;

SELECT FLOOR(12.33333) AS RESULTADO;

SELECT RAND() AS RESULTADO;

SELECT NUMERO, 
    QUANTIDADE, 
    PRECO, 
    ROUND(QUANTIDADE * PRECO, 2) AS FATURAMENTO 
FROM ITENS_NOTAS_FISCAIS;

/* Atividade Funções Matemáticas */
SELECT YEAR(DATA_VENDA), FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO)))
FROM NOTAS_FISCAIS NF INNER JOIN ITENS_NOTAS_FISCAIS INF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);