SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT * FROM NOTAS_FISCAIS;

/* Consulta com vendas de clientes por mês */
SELECT NF.CPF,
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO,
    SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS
FROM NOTAS_FISCAIS NF INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');

/* Limite de compra por cliente */
SELECT * FROM TABELA_DE_CLIENTES;

SELECT TC.CPF,
    TC.NOME, 
    TC.VOLUME_COMPRA AS QUANTIDADE_LIMITE 
FROM TABELA_DE_CLIENTES TC;

SELECT NF.CPF,
    TC.NOME,
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO,
    SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS,
    MAX(TC.VOLUME_COMPRA) AS VOLUME_LIMITE
FROM NOTAS_FISCAIS NF 
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC
ON NF.CPF = TC.CPF
GROUP BY NF.CPF,
    TC.NOME,
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');

SELECT X.CPF, 
    X.NOME, 
    X.MES_ANO, 
    X.QUANTIDADE_VENDAS, 
    X.VOLUME_LIMITE,
    CASE
        WHEN (X.QUANTIDADE_VENDAS - X.QUANTIDADE_LIMITE < 0) THEN 'INVÁLIDA'
        ELSE 'VALIDA'
    END AS STATUS_VENDA
FROM(
    SELECT NF.CPF,
        TC.NOME,
        DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS,
        MAX(TC.VOLUME_COMPRA) AS VOLUME_LIMITE
    FROM NOTAS_FISCAIS NF 
    INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON NF.NUMERO = INF.NUMERO
    INNER JOIN TABELA_DE_CLIENTES TC
    ON NF.CPF = TC.CPF
    GROUP BY NF.CPF,
        TC.NOME,
        DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') X);

/* Atividade no relatório de vendas válidas */
SELECT X.CPF, 
    X.NOME, 
    X.MES_ANO, 
    X.QUANTIDADE_VENDAS, 
    X.VOLUME_LIMITE,
    (X.QUANTIDADE_VENDAS / X.QUANTIDADE_LIMITE) * 100 AS PERCENTUAL_EXCEDIDO 
FROM(
    SELECT NF.CPF,
        TC.NOME,
        DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS,
        MAX(TC.VOLUME_COMPRA) AS VOLUME_LIMITE
    FROM NOTAS_FISCAIS NF 
    INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON NF.NUMERO = INF.NUMERO
    INNER JOIN TABELA_DE_CLIENTES TC
    ON NF.CPF = TC.CPF
    GROUP BY NF.CPF,
        TC.NOME,
        DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') X)
WHERE X.QUANTIDADE_VENDAS - X.QUANTIDADE_LIMITE < 0;