/* Quantidade vendida por sabor no ano de 2016 */
SELECT TP.SABOR,
    YEAR(NF.DATA_VENDA) AS ANO,
    SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;

/* Quantidade total */
SELECT YEAR(NF.DATA_VENDA) AS ANO,
    SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;

SELECT * FROM
    (SELECT TP.SABOR,
        YEAR(NF.DATA_VENDA) AS ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    FROM TABELA_DE_PRODUTOS TP
    INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN NOTAS_FISCAIS NF
    ON NF.NUMERO = INF.NUMERO
    WHERE YEAR(NF.DATA_VENDA) = 2016
    GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)) AS VENDAS_SABOR
INNER JOIN
    (SELECT YEAR(NF.DATA_VENDA) AS ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    FROM TABELA_DE_PRODUTOS TP
    INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN NOTAS_FISCAIS NF
    ON NF.NUMERO = INF.NUMERO
    WHERE YEAR(NF.DATA_VENDA) = 2016
    GROUP BY YEAR(NF.DATA_VENDA)) AS VENDAS_TOTAL
ON VENDAS_SABOR.ANO = VENDAS_TOTAL.ANO;

SELECT VENDAS_SABOR.SABOR,
    VENDAS_SABOR.ANO,
    VENDAS_SABOR.QUANTIDADE,
    ROUND((VENDAS_SABOR.QUANTIDADE / VENDAS_TOTAL.QUANTIDADE) * 100, 2) AS PARTICIPACAO
FROM
    (SELECT TP.SABOR,
        YEAR(NF.DATA_VENDA) AS ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    FROM TABELA_DE_PRODUTOS TP
    INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN NOTAS_FISCAIS NF
    ON NF.NUMERO = INF.NUMERO
    WHERE YEAR(NF.DATA_VENDA) = 2016
    GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)) AS VENDAS_SABOR
INNER JOIN
    (SELECT YEAR(NF.DATA_VENDA) AS ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    FROM TABELA_DE_PRODUTOS TP
    INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN NOTAS_FISCAIS NF
    ON NF.NUMERO = INF.NUMERO
    WHERE YEAR(NF.DATA_VENDA) = 2016
    GROUP BY YEAR(NF.DATA_VENDA)) AS VENDAS_TOTAL
ON VENDAS_SABOR.ANO = VENDAS_TOTAL.ANO
ORDER BY VENDAS_SANOR.QUANTIDADE DESC;

/* Atividade relatório de vendas por tamanho */
/* Quantidade por tamanho */
SELECT TP.TAMANHO,
    YEAR(NF.DATA_VENDA) AS ANO,
    SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.TAMANHO, YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;

/* Inner join */
SELECT VENDAS_TAMANHO.TAMANHO,
    VENDAS_TAMANHO.ANO,
    VENDAS_TAMANHO.QUANTIDADE,
    ROUND(VENDAS_TAMANHO.QUANTIDADE / VENDAS_TOTAL.QUANTIDADE * 100, 2) AS PARTICIPACAO
FROM
    (SELECT TP.TAMANHO,
        YEAR(NF.DATA_VENDA) AS ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    FROM TABELA_DE_PRODUTOS TP
    INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN NOTAS_FISCAIS NF
    ON NF.NUMERO = INF.NUMERO
    WHERE YEAR(NF.DATA_VENDA) = 2016
    GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)) AS VENDAS_TAMANHO
INNER JOIN
    (SELECT YEAR(NF.DATA_VENDA) AS ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    FROM TABELA_DE_PRODUTOS TP
    INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN NOTAS_FISCAIS NF
    ON NF.NUMERO = INF.NUMERO
    WHERE YEAR(NF.DATA_VENDA) = 2016
    GROUP BY YEAR(NF.DATA_VENDA)) AS VENDAS_TOTAL
ON VENDAS_TAMANHO.ANO = VENDAS_TOTAL.ANO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.TAMANHO, YEAR(DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;