USE SUCOS_VENDAS;

SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA,
    PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME FROM TABELA_DE_CLIENTES;

/* Alias */
SELECT CPF AS DOCUMENTO, NOME AS CLIENTE FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = '1000889';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Uva';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja';

SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'PET';

SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'pet';

SELECT * FROM TABELA_DE_PRODUTOS WHERE PRECO_DE_LISTA = 19.51;

SELECT * FROM TABELA_DE_PRODUTOS WHERE PRECO_DE_LISTA > 19.50 AND PRECO_DE_LISTA < 19.52;

SELECT * FROM TABELA_DE_PRODUTOS WHERE PRECO_DE_LISTA BETWEEN 19.50 AND 19.52;