SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

SELECT CPF, COUNT(*) FROM NOTAS_FISCAIS GROUP BY CPF;

SELECT DISTINCT A.CPF, A.NOME, B.CPF 
FROM TABELA_DE_CLIENTES A INNER JOIN NOTAS_FISCAIS B
ON A.CPF = B.CPF;

SELECT DISTINCT A.CPF, A.NOME, B.CPF 
FROM TABELA_DE_CLIENTES A LEFT JOIN NOTAS_FISCAIS B
ON A.CPF = B.CPF
WHERE B.CPF IS NULL;

SELECT DISTINCT A.CPF, B.CPF, B.NOME
FROM NOTAS_FISCAIS A RIGHT JOIN NOTAS_FISCAIS B
ON A.CPF = B.CPF
WHERE B.CPF IS NULL;

SELECT DISTINCT A.CPF, A.NOME, B.CPF 
FROM TABELA_DE_CLIENTES A LEFT JOIN NOTAS_FISCAIS B
ON A.CPF = B.CPF
WHERE B.CPF IS NULL AND YEAR(B.DATA_VENDA) = 2015; 