SELECT DISTINCT BAIRRO FROM tabela_de_vendedores;

SELECT * FROM TABELA_DE_CLIENTES
WHERE BAIRRO IN (SELECT DISTINCT BAIRRO FROM tabela_de_vendedores);

SELECT X.EMBALAGEM, X.PRECO_MAXIMO 
FROM (SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAXIMO FROM TABELA_DE_PRODUTOS
    GROUP BY EMBALAGEM) AS X WHERE X.PRECO_MAXIMO >= 10;