SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;

SELECT DISTINCT BAIRRO FROM tabela_de_vendedores;

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM tabela_de_vendedores;

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO FROM tabela_de_vendedores;

SELECT DISTINCT BAIRRO, NOME, 'Cliente' AS TIPO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO, NOME 'Vendedor' AS TIPO FROM tabela_de_vendedores;

/* Não funciona pelo fato do número de colunas ser diferente. */
SELECT DISTINCT BAIRRO, NOME, 'Cliente' AS TIPO, CPF FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO, NOME 'Vendedor' AS TIPO FROM tabela_de_vendedores;

/* Realizando FULL JOIN com UNION */
SELECT tabela_de_vendedores.BAIRRO,
    tabela_de_vendedores.NOME,
    DE_FERIAS,
    TABELA_DE_CLIENTES.BAIRRO,
    TABELA_DE_CLIENTES.NOME
FROM tabela_de_vendedores LEFT JOIN TABELA_DE_CLIENTES
ON tabela_de_vendedores.BAIRRO = TABELA_DE_CLIENTES.BAIRRO
UNION
SELECT tabela_de_vendedores.BAIRRO,
    tabela_de_vendedores.NOME,
    DE_FERIAS,
    TABELA_DE_CLIENTES.BAIRRO,
    TABELA_DE_CLIENTES.NOME
FROM tabela_de_vendedores RIGHT JOIN TABELA_DE_CLIENTES
ON tabela_de_vendedores.BAIRRO = TABELA_DE_CLIENTES.BAIRRO;