SELECT * FROM TABELA_DE_CLIENTES LIMIT 2, 3;

SELECT * FROM TABELA_DE_PRODUTOS LIMIT 5;

SELECT * FROM TABELA_DE_PRODUTOS LIMIT 2, 3;

/* Atividade LIMIT */
SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '2017-01-01' LIMIT 10;