SELECT * FROM TABELA_DE_CLIENTES;

SELECT ESTADO, LIMITE_CREDITO FROM TABELA_DE_CLIENTES;

SELECT ESTADO, SUM(LIMITE_CREDITO) AS LIMITE_TOTAL FROM TABELA_DE_CLIENTES GROUP BY ESTADO;

SELECT EMBALAGEM, PRECO_DE_LISTA FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS CONTADOR FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT BAIRRO, SUM(LIMITE_CREDITO) AS LIMITE FROM TABELA_DE_CLIENTES GROUP BY BAIRRO;

SELECT ESTADO, BAIRRO, SUM(LIMITE_CREDITO) AS LIMITE FROM TABELA_DE_CLIENTES
WHERE CIDADE = 'Rio de Janeiro'
GROUP BY ESTADO, BAIRRO;

SELECT ESTADO, BAIRRO, SUM(LIMITE_CREDITO) AS LIMITE FROM TABELA_DE_CLIENTES
WHERE CIDADE = 'Rio de Janeiro'
GROUP BY ESTADO, BAIRRO
ORDER BY BAIRRO;

/* Atividade GROUP BY */
SELECT MAX(QUANTIDADE) AS MAIOR_QUANTIDADE FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035';

SELECT COUNT(*) FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99;