SELECT DISTINCT * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM, TAMANHO FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja';

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM TABELA_DE_PRODUTOS;

/* Atividade DISTINCT */
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES WHERE CIDADE = 'Rio de Janeiro';