SELECT ESTADO, SUM(LIMITE_CREDITO) AS SOMA_LIMITE FROM TABELA_DE_CLIENTES
GROUP BY ESTADO;

/* Não funciona */
SELECT ESTADO, SUM(LIMITE_CREDITO) AS SOMA_LIMITE FROM TABELA_DE_CLIENTES
WHERE SOMA_LIMITE > 900000
GROUP BY ESTADO;

/* Funciona */
SELECT ESTADO, SUM(LIMITE_CREDITO) AS SOMA_LIMITE FROM TABELA_DE_CLIENTES
GROUP BY ESTADO
HAVING SUM(LIMITE_CREDITO) > 900000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) <= 80 AND MAX(PRECO_DE_LISTA) >= 5;

/* Atividade HAVING */
SELECT CPF, COUNT(*)
FROM NOTAS_FISCAIS
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY CPF
HAVING COUNT(*) > 2000;