SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Maçã%';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Maçã%' AND EMBALAGEM = 'PET';

/* Atividade LIKE */
SELECT * FROM TABELA_DE_CLIENTES WHERE NOME '%Mattos';