SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRERCO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT X.EMBALAGEM, X.MAIOR_PRECO
FROM (SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRERCO
    FROM TABELA_DE_PRODUTOS
    GROUP BY EMBALAGEM AS X)
WHERE X.MAIOR_PRECO >= 10;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRERCO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM AS X;

CREATE OR REPLACE VIEW 'VW_MAIORES_EMBALAGENS' AS
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRERCO
    FROM TABELA_DE_PRODUTOS
    GROUP BY EMBALAGEM AS X

SELECT X.EMBALAGEM, X.MAIOR_PRECO
FROM VW_MAIORES_EMBALAGENS X
WHERE X.MAIOR_PRECO >= 10;

SELECT A.NOME_DO_PRODUTO, 
    A.PRECO_DE_LISTA,
    A.EMBALAGEM, 
    B.MAIOR_PRECO,
    (A.PRECO_DE_LISTA / B.MAIOR_PRECO) * 100 AS PERCENTUAL
FROM TABELA_DE_PRODUTOS A INNER JOIN VW_MAIORES_EMBALAGENS B
ON A.EMBALAGEM = B.EMBALAGEM;