ALTER TABLE tabela_de_vendedores ADD COLUMN (DATA_DA_ADMISSAO DATE);

ALTER TABLE tabela_de_vendedores ADD COLUMN (DE_FERIAS BIT);

ALTER TABLE tabela_de_vendedores ADD PRIMARY KEY (MATRICULA);

UPDATE tabela_de_vendedores SET DATA_DA_ADMISSAO = '2014-08-15', DE_FERIAS = 0
WHERE MATRICULA = '00235';

UPDATE tabela_de_vendedores SET DATA_DA_ADMISSAO = '2013-09-17', DE_FERIAS = 1
WHERE MATRICULA = '00236';

INSERT INTO tabela_de_vendedores(MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_DA_ADMISSAO, DE_FERIAS)
VALUES('00237', 'Roberta Martins', 0.11, '2017-03-18', 1);

INSERT INTO tabela_de_vendedores(MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_DA_ADMISSAO, DE_FERIAS)
VALUES('00238', 'Péricles Alves', 0.11, '2016-02-21', 0);
