SELECT * FROM tbProdutos;

SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, SEXO, LIMITE_CREDITO,
    VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM tbCliente;

SELECT CPF, NOME FROM tbCliente;

/* LIMITAR QUANTIDADE */
SELECT CPF, NOME FROM tbCliente LIMIT 5;

/* ALIAS */
SELECT CPF AS DOCUMENTO, NOME AS CLIENTE FROM tbCliente;

/* CAMPOS NÃO ORDENADOS */
SELECT NOME, CPF, SEXO, IDADE, DATA_NASCIMENTO FROM tbCliente;

/* Atividade selecionando nome e matrícula dos vendedores */
SELECT NOME, MATRICULA FROM tabela_de_vendedores;

